### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by 42antoine** [tiger-seo/codeception-phpstorm-commandlinetool#4]
Please explain how to install and how to use it 👍

**Comment by tiger-seo** [comment]
well, you don't need this, cause PhpStorm supports cli tools base on Symfony Console for awhile now

**Comment by RdeWilde** [comment]
Can one eleborate?

**Comment by RdeWilde** [comment]
Is this abandoned?

**Comment by tiger-seo** [comment]
yep, Codeception is based on Symfony Console which is supported by PhpStorm and this is far better approach than manually doing this, so please use PhpStorm command-line tool for Codeception
